package app.simple.inure.extensions.viewmodels

import android.app.Application
import android.content.pm.PackageInfo
import android.util.Log
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.viewModelScope
import app.simple.inure.constants.Misc
import app.simple.inure.models.BatchPackageInfo
import app.simple.inure.preferences.AppearancePreferences
import app.simple.inure.preferences.GeneratedDataPreferences
import app.simple.inure.util.ColorUtils.toHexColor
import app.simple.inure.util.DateUtils.toDate
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter

open class DataGeneratorViewModel(application: Application) : PackageUtilsViewModel(application) {

    private val generatedAppDataPath: MutableLiveData<String> by lazy {
        MutableLiveData<String>()
    }

    fun getGeneratedAppData(): LiveData<String> {
        return generatedAppDataPath
    }

    private var apps: ArrayList<PackageInfo> = arrayListOf()

    fun generateAppsData(apps: ArrayList<PackageInfo>) {
        viewModelScope.launch(Dispatchers.IO) {
            delay(Misc.delay)
            this@DataGeneratorViewModel.apps = apps

            val path = applicationContext().cacheDir.absolutePath +
                    "/all_apps_generated_data.${GeneratedDataPreferences.getGeneratedDataType()}"

            if (File(path).exists()) {
                if (File(path).delete()) {
                    Log.d("AppsViewModel", "Deleted old generated file")
                }
            }

            val stringBuilder = getGeneratedString()

            FileOutputStream(path).use { fileOutputStream ->
                OutputStreamWriter(fileOutputStream).use {
                    // skip the formatting here, the viewer should format the files
                    it.write(stringBuilder.toString())
                }
            }

            generatedAppDataPath.postValue(path)
        }
    }

    @JvmName("generateAppsData1")
    fun generateAppsData(apps: ArrayList<BatchPackageInfo>) {
        val list = arrayListOf<PackageInfo>()
        apps.forEach {
            list.add(it.packageInfo)
        }
        generateAppsData(list)
    }

    private fun getGeneratedString(): StringBuilder {
        return when (GeneratedDataPreferences.getGeneratedDataType()) {
            GeneratedDataPreferences.XML -> generateXML()
            GeneratedDataPreferences.JSON -> generateJSON()
            GeneratedDataPreferences.TXT -> generateTXT()
            GeneratedDataPreferences.CSV -> generateCSV()
            GeneratedDataPreferences.HTML -> generateHTML()
            GeneratedDataPreferences.MD -> generateMD()
            else -> StringBuilder()
        }
    }

    private fun generateXML(): StringBuilder {
        val stringBuilder = StringBuilder()
        stringBuilder.append("<!-- Generated by Inure -->\r\n")
        stringBuilder.append("<!-- Total Apps: ${apps.size} -->\r\n")
        stringBuilder.append("<!-- Generated on ${System.currentTimeMillis().toDate()} -->\r\n\n")
        stringBuilder.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
        stringBuilder.append("<generated_data_of_apps>\n")

        for (app in apps) {
            // Generate xml
            stringBuilder.append("\n\t<app>\n")

            if (GeneratedDataPreferences.isGeneratedName())
                stringBuilder.append("\t\t<name>${app.applicationInfo.name}</name>\n")

            if (GeneratedDataPreferences.isGeneratedPackageName())
                stringBuilder.append("\t\t<package_name>${app.packageName}</package_name>\n")

            if (GeneratedDataPreferences.isGeneratedVersion())
                stringBuilder.append("\t\t<version_name>${app.versionName}</version_name>\n")

            if (GeneratedDataPreferences.isGeneratedInstallDate())
                stringBuilder.append("\t\t<first_install_time>${app.firstInstallTime.toDate()}</first_install_time>\n")

            if (GeneratedDataPreferences.isGeneratedUpdateDate())
                stringBuilder.append("\t\t<last_update_time>${app.lastUpdateTime.toDate()}</last_update_time>\n")

            if (GeneratedDataPreferences.isGeneratedPlayStore())
                stringBuilder.append("\t\t<play_store_link>https://play.google.com/store/apps/details?id=${app.packageName}</play_store_link>\n")

            if (GeneratedDataPreferences.isGeneratedFdroid())
                stringBuilder.append("\t\t<fdroid_link>https://f-droid.org/en/packages/${app.packageName}</fdroid_link>\n")

            stringBuilder.append("\t<app>\n")
        }

        stringBuilder.append("\n</generated_data_of_apps>")

        return stringBuilder
    }

    private fun generateTXT(): StringBuilder {
        val stringBuilder = StringBuilder()
        stringBuilder.append("// Generated by Inure\r\n")
        stringBuilder.append("// Total Apps: ${apps.size}\r\n")
        stringBuilder.append("// Generated on ${System.currentTimeMillis().toDate()}\r\n")

        for (i in apps.indices) {
            stringBuilder.append("\n\n")
            if (GeneratedDataPreferences.isGeneratedName())
                stringBuilder.append("Name: ${apps[i].applicationInfo.name}\n")

            if (GeneratedDataPreferences.isGeneratedPackageName())
                stringBuilder.append(apps[i].applicationInfo.packageName + "\n")

            if (GeneratedDataPreferences.isGeneratedVersion())
                stringBuilder.append(apps[i].versionName + "\n")

            if (GeneratedDataPreferences.isGeneratedInstallDate())
                stringBuilder.append(apps[i].firstInstallTime.toDate() + "\n")

            if (GeneratedDataPreferences.isGeneratedUpdateDate())
                stringBuilder.append(apps[i].lastUpdateTime.toDate() + "\n")

            if (GeneratedDataPreferences.isGeneratedPlayStore())
                stringBuilder.append("https://play.google.com/store/apps/details?id=${apps[i].packageName}\n")

            if (GeneratedDataPreferences.isGeneratedFdroid())
                stringBuilder.append("https://f-droid.org/en/packages/${apps[i].packageName}\n")
        }

        stringBuilder.append("\n")

        return stringBuilder
    }

    private fun generateJSON(): StringBuilder {
        val stringBuilder = StringBuilder()

        stringBuilder.append("{")
        stringBuilder.append("\n\t\"generated_by\": \"Inure\",")
        stringBuilder.append("\n\t\"total_apps\": ${apps.size},")
        stringBuilder.append("\n\t\"generated_on\": \"${System.currentTimeMillis().toDate()}\",")
        stringBuilder.append("\n\t\"apps\": [")

        for (app in apps) {
            stringBuilder.append("\n\t\t{")

            if (GeneratedDataPreferences.isGeneratedName()) {
                stringBuilder.append("\n\t\t\t\"name\": \"${app.applicationInfo.name}\",")
            }

            if (GeneratedDataPreferences.isGeneratedPackageName())
                stringBuilder.append("\n\t\t\t\"package_name\": \"${app.packageName}\",")

            if (GeneratedDataPreferences.isGeneratedVersion())
                stringBuilder.append("\n\t\t\t\"version_name\": \"${app.versionName}\",")

            if (GeneratedDataPreferences.isGeneratedInstallDate())
                stringBuilder.append("\n\t\t\t\"first_install_time\": \"${app.firstInstallTime.toDate()}\",")

            if (GeneratedDataPreferences.isGeneratedUpdateDate())
                stringBuilder.append("\n\t\t\t\"last_update_time\": \"${app.lastUpdateTime.toDate()}\",")

            if (GeneratedDataPreferences.isGeneratedPlayStore())
                stringBuilder.append("\n\t\t\t\"play_store_link\": \"https://play.google.com/store/apps/details?id=${app.packageName}\",")

            if (GeneratedDataPreferences.isGeneratedFdroid())
                stringBuilder.append("\n\t\t\t\"fdroid_link\": \"https://f-droid.org/en/packages/${app.packageName}\"")

            stringBuilder.append("\n\t\t},")
        }

        stringBuilder.append("\n\t]")
        stringBuilder.append("\n}")

        stringBuilder.append("\n")

        return stringBuilder
    }

    private fun generateCSV(): StringBuilder {
        val stringBuilder = StringBuilder()

        // Create csv headers first
        if (GeneratedDataPreferences.isGeneratedName())
            stringBuilder.append("\"Name,\"")

        if (GeneratedDataPreferences.isGeneratedPackageName())
            stringBuilder.append("\"Package Name,\"")

        if (GeneratedDataPreferences.isGeneratedVersion())
            stringBuilder.append("\"Version Name,\"")

        if (GeneratedDataPreferences.isGeneratedInstallDate())
            stringBuilder.append("\"First Install Time,\"")

        if (GeneratedDataPreferences.isGeneratedUpdateDate())
            stringBuilder.append("\"Last Update Time,\"")

        if (GeneratedDataPreferences.isGeneratedPlayStore())
            stringBuilder.append("\"Play Store Link,\"")

        if (GeneratedDataPreferences.isGeneratedFdroid())
            stringBuilder.append("\"F-Droid Link,\"")

        stringBuilder.append("\n")

        for (app in apps) {
            if (GeneratedDataPreferences.isGeneratedName())
                stringBuilder.append("\"${app.applicationInfo.name}\",")

            if (GeneratedDataPreferences.isGeneratedPackageName())
                stringBuilder.append("\"${app.packageName}\",")

            if (GeneratedDataPreferences.isGeneratedVersion())
                stringBuilder.append("\"${app.versionName}\",")

            if (GeneratedDataPreferences.isGeneratedInstallDate())
                stringBuilder.append("\"${app.firstInstallTime.toDate()}\",")

            if (GeneratedDataPreferences.isGeneratedUpdateDate())
                stringBuilder.append("\"${app.lastUpdateTime.toDate()}\",")

            if (GeneratedDataPreferences.isGeneratedPlayStore())
                stringBuilder.append("\"https://play.google.com/store/apps/details?id=${app.packageName}\",")

            if (GeneratedDataPreferences.isGeneratedFdroid())
                stringBuilder.append("\"https://f-droid.org/en/packages/${app.packageName}\",")

            stringBuilder.append("\n")
        }

        stringBuilder.append("\n")

        return stringBuilder
    }

    private fun generateHTML(): StringBuilder {
        val stringBuilder = StringBuilder()

        stringBuilder.append("<!DOCTYPE html>\r\n")
        stringBuilder.append("<html>\r\n")
        stringBuilder.append("<head>\r\n")
        stringBuilder.append("\t<title>Generated by Inure App Manager</title>\r\n")
        stringBuilder.append("\t<style>\r\n")
        stringBuilder.append("\t\ttable {\r\n")
        stringBuilder.append("\t\t\tfont-family: arial, sans-serif;\r\n")
        stringBuilder.append("\t\t\ttable-layout: fixed;\r\n")
        stringBuilder.append("\t\t\tborder-collapse: collapse;\r\n")
        stringBuilder.append("\t\t\twidth: 100%;\r\n")
        stringBuilder.append("\t\t}\r\n")
        stringBuilder.append("\t\tth, td {\r\n")
        stringBuilder.append("\t\t\ttext-align: left;\r\n")
        stringBuilder.append("\t\t\tpadding: 8px;\r\n")
        // Break words
        stringBuilder.append("\t\t\tword-wrap: break-word;\r\n")
        stringBuilder.append("\t\t}\r\n")
        stringBuilder.append("\t\ttr:nth-child(even){background-color: #f2f2f2}\r\n")
        stringBuilder.append("\t\tth {\r\n")
        stringBuilder.append("\t\t\tbackground-color: ${AppearancePreferences.getAccentColor().toHexColor()};\r\n")
        stringBuilder.append("\t\t\tcolor: white;\r\n")
        stringBuilder.append("\t\t}\r\n")
        stringBuilder.append("\t</style>\r\n")
        stringBuilder.append("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n")
        stringBuilder.append("\t<meta charset=\"UTF-8\">\r\n")
        stringBuilder.append("\t<meta name=\"description\" content=\"Generated by Inure\">\r\n")
        stringBuilder.append("\t<meta name=\"keywords\" content=\"Inure, Android, APK, App, Application, Package, Name, Version, Code, First Install Time, Last Update Time, Play Store, F-Droid\">\r\n")
        stringBuilder.append("\t<meta name=\"author\" content=\"Inure App Manager\">\r\n")
        stringBuilder.append("\t<meta name=\"theme-color\" content=\"#4CAF50\">\r\n")
        stringBuilder.append("\t<meta name=\"robots\" content=\"noindex, nofollow\">\r\n")
        stringBuilder.append("</head>\r\n")
        stringBuilder.append("<body>\r\n")
        stringBuilder.append("\t<table>\r\n")
        stringBuilder.append("\t\t<tr>\r\n")

        // Add serial number
        stringBuilder.append("\t\t\t<th style=\"width:5%\">S. No.</th>\r\n")

        if (GeneratedDataPreferences.isGeneratedName())
            stringBuilder.append("\t\t\t<th>Name</th>\r\n")

        if (GeneratedDataPreferences.isGeneratedPackageName())
            stringBuilder.append("\t\t\t<th>Package Name</th>\r\n")

        if (GeneratedDataPreferences.isGeneratedVersion())
            stringBuilder.append("\t\t\t<th>Version Name</th>\r\n")

        if (GeneratedDataPreferences.isGeneratedInstallDate())
            stringBuilder.append("\t\t\t<th>First Install Time</th>\r\n")

        if (GeneratedDataPreferences.isGeneratedUpdateDate())
            stringBuilder.append("\t\t\t<th>Last Update Time</th>\r\n")

        if (GeneratedDataPreferences.isGeneratedPlayStore())
            stringBuilder.append("\t\t\t<th>Play Store Link</th>\r\n")

        if (GeneratedDataPreferences.isGeneratedFdroid())
            stringBuilder.append("\t\t\t<th>F-Droid Link</th>\r\n")

        stringBuilder.append("\t\t</tr>\r\n")

        for (app in apps) {
            stringBuilder.append("\t\t<tr>\r\n")

            // Add serial number
            stringBuilder.append("\t\t\t<td>${apps.indexOf(app) + 1}</td>\r\n")

            if (GeneratedDataPreferences.isGeneratedName())
                stringBuilder.append("\t\t\t<td>${app.applicationInfo.name}</td>\r\n")

            if (GeneratedDataPreferences.isGeneratedPackageName())
                stringBuilder.append("\t\t\t<td>${app.packageName}</td>\r\n")

            if (GeneratedDataPreferences.isGeneratedVersion())
                stringBuilder.append("\t\t\t<td>${app.versionName}</td>\r\n")

            if (GeneratedDataPreferences.isGeneratedInstallDate())
                stringBuilder.append("\t\t\t<td>${app.firstInstallTime.toDate()}</td>\r\n")

            if (GeneratedDataPreferences.isGeneratedUpdateDate())
                stringBuilder.append("\t\t\t<td>${app.lastUpdateTime.toDate()}</td>\r\n")

            if (GeneratedDataPreferences.isGeneratedPlayStore())
                stringBuilder.append("\t\t\t<td><a href=\"https://play.google.com/store/apps/details?id=${app.packageName}\">Play Store</a></td>\r\n")

            if (GeneratedDataPreferences.isGeneratedFdroid())
                stringBuilder.append("\t\t\t<td><a href=\"https://f-droid.org/en/packages/${app.packageName}\">F-Droid</a></td>\r\n")

            stringBuilder.append("\t\t</tr>\r\n")
        }

        stringBuilder.append("\t</table>\r\n")
        stringBuilder.append("</body>\r\n")
        stringBuilder.append("</html>\r\n")

        return stringBuilder
    }

    private fun generateMD(): StringBuilder {
        val stringBuilder = StringBuilder()

        stringBuilder.append("# Inure\r\n")
        stringBuilder.append("Generated by Inure App Manager\r\n")
        stringBuilder.append("## Generated Data\r\n")

        stringBuilder.append("|")

        // Add serial number
        stringBuilder.append(" S. No. |")

        if (GeneratedDataPreferences.isGeneratedName())
            stringBuilder.append(" Name |")

        if (GeneratedDataPreferences.isGeneratedPackageName())
            stringBuilder.append(" Package Name |")

        if (GeneratedDataPreferences.isGeneratedVersion())
            stringBuilder.append(" Version Name |")

        if (GeneratedDataPreferences.isGeneratedInstallDate())
            stringBuilder.append(" First Install Time |")

        if (GeneratedDataPreferences.isGeneratedUpdateDate())
            stringBuilder.append(" Last Update Time |")

        if (GeneratedDataPreferences.isGeneratedPlayStore())
            stringBuilder.append(" Play Store Link |")

        if (GeneratedDataPreferences.isGeneratedFdroid())
            stringBuilder.append(" F-Droid Link |")

        stringBuilder.append("\r\n")

        stringBuilder.append("|")

        if (GeneratedDataPreferences.isGeneratedName())
            stringBuilder.append(" --- |")

        if (GeneratedDataPreferences.isGeneratedPackageName())
            stringBuilder.append(" --- |")

        if (GeneratedDataPreferences.isGeneratedVersion())
            stringBuilder.append(" --- |")

        if (GeneratedDataPreferences.isGeneratedInstallDate())
            stringBuilder.append(" --- |")

        if (GeneratedDataPreferences.isGeneratedUpdateDate())
            stringBuilder.append(" --- |")

        if (GeneratedDataPreferences.isGeneratedPlayStore())
            stringBuilder.append(" --- |")

        if (GeneratedDataPreferences.isGeneratedFdroid())
            stringBuilder.append(" --- |")

        stringBuilder.append("\r\n")

        for (app in apps) {
            stringBuilder.append("|")

            // Add serial number
            stringBuilder.append(" ${apps.indexOf(app) + 1} |")

            if (GeneratedDataPreferences.isGeneratedName())
                stringBuilder.append(" ${app.applicationInfo.name} |")

            if (GeneratedDataPreferences.isGeneratedPackageName())
                stringBuilder.append(" ${app.packageName} |")

            if (GeneratedDataPreferences.isGeneratedVersion())
                stringBuilder.append(" ${app.versionName} |")

            if (GeneratedDataPreferences.isGeneratedInstallDate())
                stringBuilder.append(" ${app.firstInstallTime.toDate()} |")

            if (GeneratedDataPreferences.isGeneratedUpdateDate())
                stringBuilder.append(" ${app.lastUpdateTime.toDate()} |")

            if (GeneratedDataPreferences.isGeneratedPlayStore())
                stringBuilder.append(" [Play Store](https://play.google.com/store/apps/details?id=${app.packageName}) |")

            if (GeneratedDataPreferences.isGeneratedFdroid())
                stringBuilder.append(" [F-Droid](https://f-droid.org/en/packages/${app.packageName}) |")

            stringBuilder.append("\r\n")
        }

        return stringBuilder
    }

    fun clearGeneratedAppsDataLiveData() {
        generatedAppDataPath.postValue(null)
    }
}