import json
import os
import time
import urllib.request

json_file = "trackers.json"
output_file = "trackers.xml"

# Download the JSON file from Exodus: https://reports.exodus-privacy.eu.org/api/trackers
# and save it in the same folder as this script and show download progress
decision = "y"
startTimeMillis = time.time()

if decision.lower() == "y":
    # Delete the existing JSON file
    try:
        os.remove(json_file)
    except FileNotFoundError:
        pass

    print("Downloading", json_file, "from Exodus...")
    with urllib.request.urlopen("https://reports.exodus-privacy.eu.org/api/trackers") as response:
        with open(json_file, "wb") as file:
            file.write(response.read())
            file.close()
            print("Downloaded", json_file)

# Format the JSON file
print("Formatting", json_file, "...")
with open(json_file, "r+", encoding="utf8") as file:
    json_content = json.load(file)
    json_content = json.dumps(json_content, indent=4, sort_keys=True)
    file.seek(0)
    file.write(json_content)

# Read the JSON file
with open(json_file, "r", encoding="utf8") as file:
    json_content = json.load(file)

# Extract the website tags
signatures = [tracker["code_signature"] for tracker in json_content["trackers"].values()]
websites = [tracker["website"] for tracker in json_content["trackers"].values()]
names = [tracker["name"] for tracker in json_content["trackers"].values()]
print("Total signatures:", len(signatures))

# Format the output
output = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
output += '<resources>\n\n'
output += "\t<!-- This file is auto-generated by the parser.py script\n"
output += "\t        located in the trackers folder. -->\n\n"
output += "\t<!-- Total trackers: " + str(len(signatures)) + " -->\n\n"
output += '\t<string-array name="trackers">\n'
output += "\n".join([f'\t\t<item>{website}</item> <!-- '
                     f'{signatures.index(website) + 1} -->' for website in signatures])
output += "\n\t</string-array>"

output += "\n\n<!-- Total websites: " + str(len(websites)) + " -->\n\n"
output += '\t<string-array name="websites">\n'
output += "\n".join([f'\t\t<item>{website}</item> <!-- '
                     f'{websites.index(website) + 1} -->' for website in websites])
output += "\n\t</string-array>"

output += "\n\n<!-- Total names: " + str(len(names)) + " -->\n\n"
output += '\t<string-array name="names">\n'
output += "\n".join([f'\t\t<item>{name}</item> <!-- '
                     f'{names.index(name) + 1} -->' for name in names])
output += "\n\t</string-array>"
output += "\n\n</resources>"

# Write the output to the text file
with open(output_file, "w") as file:
    file.write(output)

print("Output written to", output_file)

# Copy the file to \Inure\app\src\main\res\values\trackers.xml
# The path Inure is one level above the trackers folder

# Check if the file exists
if decision.lower() == "y":
    try:
        open(f"..\\..\\app\\src\\main\\res\\values\\{output_file}", "r")
        print("File already exists at: ..\\..\\app\\src\\main\\res\\values\\trackers.xml")
        print("Deleting..")
        os.remove(f"..\\..\\app\\src\\main\\res\\values\\{output_file}")
    except FileNotFoundError:
        print("File not found at: ..\\..\\app\\src\\main\\res\\values\\trackers.xml")
    finally:
        os.system(f"copy {output_file} ..\\..\\app\\src\\main\\res\\values\\trackers.xml")
        print("Copied to: ..\\..\\app\\src\\main\\res\\values\\trackers.xml")

print("Total time taken:", round(time.time() - startTimeMillis, 2), "seconds")

# Open the output file
os.startfile(output_file)
