package app.simple.inure.constants

object BundleConstants {
    const val batchUninstallerProgressStateModel = "batchUninstallerProgressStateModel"
    const val text = "text_only"
    const val firstLaunch = "first_launch"
    const val error = "error"
    const val pathToImage = "path_of_image"
    const val pathToApk = "path_of_apk"
    const val goBack = "go_back"
    const val path: String = "path"
    const val isRaw: String = "is_raw"
    const val certificate: String = "certificate"
    const val uri: String = "uri"
    const val file: String = "file"
    const val warning: String = "warning"
    const val loading: String = "loading"
    const val trackersMessage: String = "trackers_message"
    const val className = "class_name"
    const val packageInfo = "package_info"
    const val permissionInfo = "permission_info"
    const val activityInfo = "activity_info"
    const val providerInfo = "provider_info"
    const val serviceInfo = "service_info"
    const val packageId = "package_id"
    const val isManifest = "is_manifest"
    const val pathToXml = "path_to_xml"
    const val pathToJSON = "path_to_json"
    const val pathToJava = "path_to_java"
    const val transitionName = "transition_name"
    const val permissionMode = "permission_mode"
    const val componentMode = "component_state_mode"
    const val webPage = "web_page_name"
    const val canPaste = "terminal_can_paste"
    const val wifilock: String = "wifi_lock_state"
    const val wakelock: String = "wake_lock_state"
    const val selectedBatchApps = "selected_batch_apps"
}