package app.simple.inure.constants

object Extensions {

    /**
     * List of all the image extensions
     */
    val imageExtensions = hashMapOf(
            "jpg" to true,
            "jpeg" to true,
            "png" to true,
            "gif" to true,
            "webp" to true,
            "bmp" to true,
            "wbmp" to true,
            "ico" to true,
            "svg" to true,
            "svgz" to true,
            "tiff" to true,
            "tif" to true,
            "jpe" to true,
            "jfif" to true,
            "dib" to true,
            "heif" to true,
            "heic" to true,
            "cur" to true,
            "fif" to true,
            "psd" to true,
            "pspimage" to true,
            "xcf" to true,
            "apng" to true,
            "avif" to true,
            "jng" to true,
            "mng" to true,
            "pcx" to true,
            "pic" to true,
            "raw" to true,
            "tga" to true,
            "dds" to true,
            "exr" to true,
            "hdr" to true,
            "jxr" to true,
            "pam" to true,
            "pgf" to true,
            "sgi" to true,
            "rgb" to true,
            "rgba" to true,
            "bw" to true,
            "int" to true,
            "inta" to true,
            "sid" to true,
            "ras" to true,
            "sun" to true,
            "tga" to true,
            "xbm" to true,
            "xpm" to true,
            "3dv" to true,
            "amf" to true,
            "ai" to true,
            "awg" to true,
            "cgm" to true,
            "cdr" to true,
            "cmx" to true,
            "dxf" to true,
            "e2d" to true,
            "egt" to true,
            "eps" to true,
            "fs" to true,
            "gbr" to true,
            "odg" to true,
            "svg" to true,
            "stl" to true,
            "vrml" to true,
            "x3d" to true,
    )
}