name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set the appropriate Java version here

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleDebug  # You can change 'assembleDebug' to the desired build task

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk  # Update the path to your APK

