name: Build APK (Beta)

on:
    workflow_dispatch:  # Allow manual triggering
    push:
        branches:
            - master
        paths-ignore:
            - 'fastlane/**'
            - 'scripts/**'
            - '.idea/**'
            - '.github/**'
            - 'assets/**'
            - '*.md'
            - '*.yml'

jobs:

    build:
        # Skip if head commit contains 'skip build apk'
        if: "!contains(github.event.head_commit.message, 'skip build apk')"
        name: Build APK
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '17'
                    cache: 'gradle'

            -   name: Decode Keystore
                id: decode_keystore
                uses: timheuer/base64-to-file@v1
                with:
                    fileName: 'keystore/key.jks'
                    encodedString: ${{ secrets.SIGN_KEY }}

            #      - name: Set up Android
            #        uses: actions/setup-android@v2
            #        with:
            #          sdk-platform: 34   # Specify the desired Android SDK platform version
            #          ndk-version: '25.2.9519653'  # Specify the desired NDK version

            -   name: Build APK
                run: | # Use 'bundleRelease' to build the release bundle
                    chmod +x ./gradlew
                    ./gradlew clean assembleBetaRelease
                env:
                    SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
                    SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
                    SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

            -   name: Send APK to Telegram
                uses: appleboy/telegram-send-action@master
                with:
                    to: inure_app_manager
                    token: ${{ secrets.TG_BOT_KEY }}
                    message: 'New Beta APK build is ready, test it and report any bugs or issue you had found in the group!'
                    files: |
                        app/**/*.apk

            -   name: Archive APK
                uses: actions/upload-artifact@v3
                with:
                    name: Beta APK (Debug)
                    path: app/**/*.apk

